"""create enclosures table

Revision ID: a1570ac9d51c
Revises: 44adc0dfa35b
Create Date: 2023-05-01 10:48:32.523046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1570ac9d51c'
down_revision = '44adc0dfa35b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enclosures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('environment', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('open_to_visitors', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enclosures', schema=None) as batch_op:
        batch_op.drop_column('open_to_visitors')
        batch_op.drop_column('environment')

    # ### end Alembic commands ###
