"""finish zookeepers table

Revision ID: f213a03c8e73
Revises: a1570ac9d51c
Create Date: 2023-05-01 10:55:53.531132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f213a03c8e73'
down_revision = 'a1570ac9d51c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zookeepers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('birthday', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zookeepers', schema=None) as batch_op:
        batch_op.drop_column('birthday')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
